### PR TITLE
Add support for Maya 2018

### PR DESCRIPTION
**Pull request by davvid**

### CODE REVIEW

**Comment by andrewkww** [comment]
Thanks for the pull request! Since I don't have access to Maya 2018 yet, I have a few questions about 00829d55d507b5f759db91b96d4c1d075abccd6e.

As of Maya 2017, methods like `MPxNode::getInternalValue` and `MPxNode::setInternalValue` were supposed to be obsolete, and custom nodes were supposed to use the `MPxNode::getInternalValueInContext` and `MPxNode::setInternalValueInContext`, which uses `MDGContext`. Has the use of MDGContext been changed in Maya 2018?

The commit also changes several forward declarations into `#include`. I try to use forward declarations wherever possible. So I'm curious whether those forward declarations have to be be converted to `#include`?

**Comment by davvid** [comment]
Yeah, it's kinda surprising regarding `{get,set}InternalValueInContext` -- the API guidelines changed in 2018 and now the ones that take the `MDGContext` are deprecated.  At $dayjob, we skipped over 2017 and are transitioning from 2016 to 2018 so that one surprised us too.

To avoid warnings on older versions we ifdef it so that the "new" API style is only used on 2018.

Regarding the forward declarations -- in 2018 everything moved into a custom namespace so it's no longer possible to forward-declare maya classes.  We have to include their headers instead.  For that one it was a question of whether it was worth having an ifdef to choose between forward declarations and full-on includes. It seemed simpler to just include the headers and avoid another block of ifdefs.

Let me know if you have any more questions or sugs.   Cheers, and thanks for the review!

**Comment by andrewkww** [comment]
I see. Your changes make sense now. I made a few more minor changes here:
https://github.com/andrewkww/HoudiniEngineForMaya/commits/davvid/maya2018

The changes for `AssetNode::internalArrayCount` breaks older Maya versions, so I put the old version into `#else` instead.

There were a few other forward declarations in other files that should probably be removed as well.

Could you see if these changes still compile in Maya 2018?

**Comment by davvid** [comment]
Sweet, I'll take a stab at compiling tomorrow and let you know how it goes.

**Comment by davvid** [comment]
@andrewkww I just pushed up a new version of my branch.  It includes your two commits, and then an additional commit to `AssetNode.C` which makes both variants of `internalArrayCount()` visible to the compiler.

In Maya2018 the base class provides both, so we have to implement both in order to avoid shadowing warnings.  Before this change we were getting an undefined symbol due to a mismatch between the ifdefs in the header and the implementation.

Let me know if that's looking good on your side.  I tested compiling against both 2016 and 2018.

**Comment by andrewkww** [comment]
Merged! Thanks for the help!

**Pull request merged**
