### PR TITLE
Warning free compilation on Linux

### PR DESCRIPTION
**Pull request by robpieke**
Mostly signed-vs-unsigned, followed by unused variables, followed by class member initialisation order.

Building against 13.0.444 on Sat 14 Jun

### CODE REVIEW

**Comment by robpieke** [comment]
Does this show up in the pull request for you now? I admit this is my first real use of Github :)

**Comment by andrewkww** [comment]
Yup, they are showing up as two separate commits though. Could you try to amend the original commits instead? That way the lines were never actually removed, and slightly cleaner. I don't think you can do this through the GitHub interface, but you can do this with git itself: https://help.github.com/articles/about-git-rebase

**Comment by robpieke** [comment]
ugh ... okay, i won't open up the debate about rebase being evil ;)
will rebase tomorrow.

**Comment by robpieke** [comment]
okay, i've tried. rebasing on pushed code is messy :(
it'd be great if you could pull&merge (or otherwise integrate) these changes before things start to diverge.

**Comment by andrewkww** [comment]
Awesome! I've merged 15846008675749f616867ae92a98100c2502bb95. Thanks!

I think the rebase squash/fixup was done correctly. The mess probably came from trying to push the updated branch. It seems like a pull was done before the push. But in this case, you probably didn't need the pull. You simply had to force the push and clobber the previous branch and commits.

Keep the pull requests coming! Thanks!

**Pull request closed without merging**
